// USERS
export const GET_GITHUB_USER_BASIC_INFO = "GET_GITHUB_USER_BASIC_INFO";
export const GET_ALL_USER_COMMITS = "GET_ALL_USER_COMMITS";
export const GET_USER_MOST_FREQUENTLY_USED_LANGUAGES =
  "GET_USER_MOST_FREQUENTLY_USED_LANGUAGES";
